# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "public_network"
  config.vm.hostname = "isecu-minion"
  config.vm.network "public_network", ip: "192.168.1.92"
  config.vm.network "private_network", ip: "192.168.4.92",  virtualbox__intnet: true
  config.vm.network "forwarded_port", guest: 22, host: 2292
config.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
end

config.vm.provision "shell", inline: <<-SHELL
  apt-get update -y
  apt-get install -y fish zsh fzf docker.io docker-compose git avahi-daemon 
  docker pull portainer/portainer:latest
  docker volume create portainer_data
  docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data --name portainer portainer/portainer:latest
  echo "portainer_url: https://localhost:9000"


  # /vagrant/1-shells-framework/zsh-framework.sh <<< "Yes"
  # /vagrant/1-shells-framework/2-zsh-plugs.sh
SHELL
end