# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.define "trunksip"
  config.vm.hostname = "trunksip"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "trunksip"
    vb.memory = "2048"
  end

  # config.ssh.username="vagrant"
  # config.ssh.password="vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y asterix
    cd /vagrant && ./init_voix_asterix.sh
  SHELL
end
