# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "isecu-minion-hardening"
  config.vm.network "public_network", ip: "192.168.1.92"
  config.vm.network "private_network", ip: "192.168.100.52",  virtualbox__intnet: true
  # config.vm.network "private_network", ip: "192.168.101.52",  virtualbox__intnet: true
  # config.vm.network "private_network", ip: "192.168.102.52",  virtualbox__intnet: true
  config.vm.network "forwarded_port", guest: 22, host: 2292
config.vm.provider "virtualbox" do |vb|
  vb.memory = "1048"
  vb.cpus="2"
  vb.gui = true
end

config.vm.provision "shell", inline: <<-SHELL
  apt-get update -y
  apt-get install -y fish zsh fzf docker.io docker-compose git avahi-daemon 

  # /vagrant/1-shells-framework/zsh-framework.sh <<< "Yes"
  # /vagrant/1-shells-framework/2-zsh-plugs.sh

  # zellij bat lunarvim 
  # curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash
  # filebrowser -a 0.0.0.0 -r $(pwd) 

SHELL
end