# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "xenomii/pfsense-2.6.0"
  config.vm.hostname = "isecu-minion-pfsense"
  config.vm.network "public_network", ip: "192.168.1.91"
  config.vm.network "private_network", ip: "192.168.100.254",  virtualbox__intnet: true
  config.vm.network "private_network", ip: "192.168.101.254",  virtualbox__intnet: true
  config.vm.network "private_network", ip: "192.168.102.254",  virtualbox__intnet: true
  config.vm.network "forwarded_port", guest: 22, host: 22254
config.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  vb.cpus = "2"
  vb.gui = true
end

config.vm.provision "shell", inline: <<-SHELL

  echo "test"
  sudo pfctl -d
  sudo /etc/rc.initial.password

SHELL
end