# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "xenomii/pfsense-2.6.0"
  config.vm.network "public_network"
  config.vm.hostname = "isecu-minion-pfsense"
  config.vm.network "public_network", ip: "192.168.1.91"
  config.vm.network "private_network", ip: "192.168.100.254",  virtualbox__intnet: true
  config.vm.network "private_network", ip: "192.168.101.254",  virtualbox__intnet: true
  config.vm.network "private_network", ip: "192.168.102.254",  virtualbox__intnet: true
  config.vm.network "forwarded_port", guest: 22, host: 22254
config.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  vb.cpus = "2"
end

config.vm.provision "shell", inline: <<-SHELL

  echo "test"
  # apt-get update -y
  # apt-get install -y fish zsh fzf docker.io docker-compose git avahi-daemon 
  # docker pull portainer/portainer:latest
  # docker volume create portainer_data
  # docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data --name portainer portainer/portainer:latest
  # echo "portainer_url: http://$(hostname):9000"


  # /vagrant/1-shells-framework/zsh-framework.sh <<< "Yes"
  # /vagrant/1-shells-framework/2-zsh-plugs.sh

  # zellij bat lunarvim 
  # curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash
  # filebrowser -a 0.0.0.0 -r $(pwd) 

SHELL
end